### ISSUE TITLE
Regarding issues that arise during training.

### ISSUE THREAD

**Issue by Nemophilist98** [KwanWaiPang/DPVO_comment#1]
Hello, I encountered the following issue during training:

```
`-----
datasets/TartanAir/neighborhood/neighborhood/Hard/P000/image_left/000000_left.png
-----
[   300,  0.0000128]    21.1356,     0.0000,     0.1065,     0.0000,     0.0000,     1.0000,     1.0000,     1.0000,     1.0000, 
datasets/TartanAir/office/office/Easy/P004/image_left/000000_left.png
-----
datasets/TartanAir/neighborhood/neighborhood/Hard/P011/image_left/000000_left.png
-----
datasets/TartanAir/gascola/gascola/Easy/P003/image_left/000000_left.png
-----
Traceback (most recent call last):
  File "/home/doujiarui/DPVO/train.py", line 173, in <module>
    train(args)
  File "/home/doujiarui/DPVO/train.py", line 77, in train
    for data_blob in train_loader:
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
    return self._process_data(data)
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 235, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/doujiarui/DPVO/dpvo/data_readers/base.py", line 162, in __getitem__
    images = np.stack(images).astype(np.float32)
  File "<__array_function__ internals>", line 180, in stack
  File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape`
```

I have ruled out the issue with the data, and now I don't know where the problem lies. Have you encountered it before?
Can you add a contact information? I am also researching DPVO.

v: 13364021606

**Comment by Nemophilist98** [comment]
> Hello, I encountered the following issue during training:
> 
> ```
> `-----
> datasets/TartanAir/neighborhood/neighborhood/Hard/P000/image_left/000000_left.png
> -----
> [   300,  0.0000128]    21.1356,     0.0000,     0.1065,     0.0000,     0.0000,     1.0000,     1.0000,     1.0000,     1.0000, 
> datasets/TartanAir/office/office/Easy/P004/image_left/000000_left.png
> -----
> datasets/TartanAir/neighborhood/neighborhood/Hard/P011/image_left/000000_left.png
> -----
> datasets/TartanAir/gascola/gascola/Easy/P003/image_left/000000_left.png
> -----
> Traceback (most recent call last):
>   File "/home/doujiarui/DPVO/train.py", line 173, in <module>
>     train(args)
>   File "/home/doujiarui/DPVO/train.py", line 77, in train
>     for data_blob in train_loader:
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
>     data = self._next_data()
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
>     return self._process_data(data)
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
>     data.reraise()
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
>     raise exception
> ValueError: Caught ValueError in DataLoader worker process 3.
> Original Traceback (most recent call last):
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 235, in __getitem__
>     return self.datasets[dataset_idx][sample_idx]
>   File "/home/doujiarui/DPVO/dpvo/data_readers/base.py", line 162, in __getitem__
>     images = np.stack(images).astype(np.float32)
>   File "<__array_function__ internals>", line 180, in stack
>   File "/home/doujiarui/anaconda3/envs/dpvo/lib/python3.10/site-packages/numpy/core/shape_base.py", line 426, in stack
>     raise ValueError('all input arrays must have the same shape')
> ValueError: all input arrays must have the same shape`
> ```
> 
> I have ruled out the issue with the data, and now I don't know where the problem lies. Have you encountered it before? Can you add a contact information? I am also researching DPVO.
> 
> v: 13364021606
